# Generated by Django 4.1.2 on 2022-10-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, 'in Progress'), (2, 'Deleted'), (3, 'Fineshed')], default=1),
        ),
    ]
